### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by bzz** [src-d/vecino#1] opened 2017-07-19 09:54 UTC
`pip3 install -r requirements.txt` results in error in CLI

### Logs
```
Obtaining bblfsh from git+git://github.com/bblfsh/client-python.git@v0.0.3#egg=bblfsh (from -r requirements.txt (line 1))
  Updating ./.venv/src/bblfsh clone (to v0.0.3)
Obtaining ast2vec from git+git://github.com/src-d/ast2vec.git@develop#egg=ast2vec (from -r requirements.txt (line 2))
  Updating ./.venv/src/ast2vec clone (to develop)
Collecting wmd>=1.2.4 (from -r requirements.txt (line 3))
  Using cached wmd-1.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rx/z9zyr71d70x92zwbn3rrjx4c0000gn/T/pip-build-8k90vv9s/wmd/setup.py", line 3, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rx/z9zyr71d70x92zwbn3rrjx4c0000gn/T/pip-build-8k90vv9s/wmd/
```

### Steps to reproduce
```
 git clone https://github.com/src-d/vecino.git; cd vecino; git checkout develop
 virtualenv -p python3 .venv
 source .venv/bin/activate
 pip3 install -r requirements.txt
 echo $?
```
Expected result: 0

Actual result: 1

### Update
Even after manually installing `numpy` it fails without `-e git://github.com/src-d/modelforge.git@develop#egg=modelforge`

**Comment by bzz** [comment] 2017-07-19 09:58
Tried adding `numpy>=1.12,<2.0` to `requirements.txt` but that did not help solving the issue.

**Comment by fineguy** [comment] 2017-07-19 10:34
Can't reproduce, I get a different problem:
```
Collecting modelforge>=1.0.0 (from ast2vec->-r requirements.txt (line 2))
  Could not find a version that satisfies the requirement modelforge>=1.0.0 (from ast2vec->-r requirements.txt (line 2)) (from versions: )
No matching distribution found for modelforge>=1.0.0 (from ast2vec->-r requirements.txt (line 2))
```
Which is fixed by adding `-e git://github.com/src-d/modelforge.git@develop#egg=modelforge` at the beginning of `requirements.txt`

**Comment by bzz** [comment] 2017-07-19 10:36
@fineguy thx for checking! Just to make sure - did you used virtualenv as well?

**Comment by fineguy** [comment] 2017-07-19 10:47
Hmm, interesting...
The output in my first reply is from docker on science-3. But if I try to do it locally on my Mac I get the same output as you. 
It seems there's some issues with `wmd` package, cause I can't install it separately either. The only workaround I know of is to install `numpy` beforehand.

**Comment by bzz** [comment] 2017-07-19 10:53
Thanks for verifying the issue!

Strange enough, manually `pip3 install numpy` before doing `pip3 -r` is a workaround, but putting `numpy>=1.12,<2.0` to the first line of `requirements.txt` is not :/

Indeed, it might be an issue in https://github.com/src-d/wmd-relax now, as soon as it's verified, let's wait for @vmarkovtsev to triage.

**Comment by bzz** [comment] 2017-07-19 11:31
Indeed, after manually installed `numpy` it still fails untill

`-e git://github.com/src-d/modelforge.git@develop#egg=modelforge` is added to `requirments.txt`

**Comment by vmarkovtsev** [comment] 2017-07-19 12:38
Manually pip3 install numpy before doing pip3 -r is the supposed workaround. Whatever I do, this will still always fail. I will add a message about numpy but I guess few people will read it. The reason behind this is the way pip install works.

Modelforge shall be installed separately for now. When we will have GCS buckets, I will be able to release the packages on pypi and this problem will go away.

Anyway, if in trouble, please see .travis.yml as we always pass CI here.

Finally, vecino was not updated for the most recent changes in ast2vec and will fail as it failed on the engineering demo. I am having meetings today, so will not be able to fix it until this evening.

**Comment by vmarkovtsev** [comment] 2017-07-19 12:39
Oh, and yes: since we do not have GCS buckets, no way you can easily run vecino at all. Please come to me and I tell you the name of the secret bucket.

**Comment by vmarkovtsev** [comment] 2017-09-16 20:45
This is completely resolved. numpy is still needed.

**Closed by vmarkovtsev** 2017-09-16 20:45 UTC
